version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Terraform..."
      - curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
      - apt-get update && apt-get install -y zip

  pre_build:
    commands:
      - echo "Packaging Lambda function..."
      - chmod +x scripts/package_lambdas.sh
      - ./scripts/package_lambdas.sh

  build:
    commands:
      - echo "Deploying infrastructure via Terraform..."
      - cd infra
      - terraform init -input=false
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Build completed successfully"
      - ls -l ../dist

artifacts:
  base-directory: dist
  files:
    - "**/*"
